"""empty message

Revision ID: 0bb3325c25d0
Revises: 34030eea7198
Create Date: 2017-07-11 11:11:45.390759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bb3325c25d0'
down_revision = '34030eea7198'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dmis_layers', sa.Column('layer_copyright', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dmis_layers', 'layer_copyright')
    # ### end Alembic commands ###
