"""empty message

Revision ID: 34030eea7198
Revises: 5e5ed51ab364
Create Date: 2017-06-27 16:12:29.437901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34030eea7198'
down_revision = '5e5ed51ab364'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dmis_layers',
    sa.Column('layer_id', sa.BigInteger(), nullable=False),
    sa.Column('layer_name', sa.String(), nullable=True),
    sa.Column('layer_title', sa.String(), nullable=True),
    sa.Column('layer_description', sa.String(), nullable=False),
    sa.Column('layer_group', sa.String(), nullable=False),
    sa.Column('map_category', sa.Integer(), nullable=False),
    sa.Column('layer_source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('layer_id')
    )
    op.create_index(op.f('ix_dmis_layers_layer_id'), 'dmis_layers', ['layer_id'], unique=False)
    op.create_index(op.f('ix_dmis_layers_layer_name'), 'dmis_layers', ['layer_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    op.drop_table('dmis_layers')
    # ### end Alembic commands ###
