"""empty message

Revision ID: 42b49f9fd9eb
Revises: e3976bc2ca4d
Create Date: 2017-08-28 14:03:50.757472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42b49f9fd9eb'
down_revision = 'e3976bc2ca4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dmis_layers', sa.Column('layer_style', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dmis_layers', 'layer_style')
    # ### end Alembic commands ###
