"""empty message

Revision ID: 5e1509728327
Revises: a4b508b74727
Create Date: 2017-10-06 15:59:54.504635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e1509728327'
down_revision = 'a4b508b74727'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dmis_layers', sa.Column('layer_geometry_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dmis_layers', 'layer_geometry_type')
    # ### end Alembic commands ###
