"""empty message

Revision ID: 5e5ed51ab364
Revises: 
Create Date: 2017-06-16 17:15:44.356791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e5ed51ab364'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dmis_users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('email_address', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_dmis_users_user_id'), 'dmis_users', ['user_id'], unique=False)
    op.create_index(op.f('ix_dmis_users_username'), 'dmis_users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dmis_users_username'), table_name='dmis_users')
    op.drop_index(op.f('ix_dmis_users_user_id'), table_name='dmis_users')
    op.drop_table('dmis_users')
    # ### end Alembic commands ###
