"""empty message

Revision ID: 8abd6b75b9d9
Revises: b0e9dc7fb763
Create Date: 2017-07-25 12:48:38.737392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8abd6b75b9d9'
down_revision = 'b0e9dc7fb763'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dmis_layers', 'layer_description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dmis_layers', sa.Column('layer_description', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
