"""empty message

Revision ID: 9a4c12be26d0
Revises: abc2e0ccd096
Create Date: 2017-07-19 11:14:49.243644

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9a4c12be26d0'
down_revision = 'abc2e0ccd096'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Canals')
    op.add_column('dmis_layers', sa.Column('layer_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dmis_layers', 'layer_type')
    op.create_table('Canals',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Canals_id_seq"\'::regclass)'), nullable=False),
    sa.Column('geom', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('code', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('describe', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Canals_pkey')
    )
    # ### end Alembic commands ###
