python"""empty message

Revision ID: abc2e0ccd096
Revises: bc2d1f8b2cc8
Create Date: 2017-07-13 09:48:05.069191

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'abc2e0ccd096'
down_revision = 'bc2d1f8b2cc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dmis_data',
    sa.Column('data_id', sa.BigInteger(), nullable=False),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.Column('json_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('data_id')
    )
    op.create_index(op.f('ix_dmis_data_data_id'), 'dmis_data', ['data_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dmis_data_data_id'), table_name='dmis_data')
    op.drop_table('dmis_data')
    # ### end Alembic commands ###
