"""empty message

Revision ID: b0e9dc7fb763
Revises: 9a4c12be26d0
Create Date: 2017-07-19 11:52:19.143282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0e9dc7fb763'
down_revision = '9a4c12be26d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dmis_layers', 'layer_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dmis_layers', 'layer_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
