"""empty message

Revision ID: bc2d1f8b2cc8
Revises: 0bb3325c25d0
Create Date: 2017-07-12 15:29:21.820785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc2d1f8b2cc8'
down_revision = '0bb3325c25d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dmis_users', 'email_address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dmis_users', sa.Column('email_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
