"""empty message

Revision ID: c87725d103ab
Revises: 8abd6b75b9d9
Create Date: 2017-08-15 12:15:25.377898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c87725d103ab'
down_revision = '8abd6b75b9d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dmis_data', sa.Column('data_received', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dmis_data', 'data_received')
    # ### end Alembic commands ###
