"""empty message

Revision ID: e3976bc2ca4d
Revises: c87725d103ab
Create Date: 2017-08-24 15:49:58.051821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3976bc2ca4d'
down_revision = 'c87725d103ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dmis_layer_info',
    sa.Column('layer_id', sa.Integer(), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('layer_title', sa.String(), nullable=True),
    sa.Column('layer_group', sa.String(), nullable=False),
    sa.Column('layer_copyright', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['layer_id'], ['dmis_layers.layer_id'], ),
    sa.PrimaryKeyConstraint('layer_id', 'locale')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dmis_layer_info')
    # ### end Alembic commands ###
